version: '3.4'

services:  
  polly:
    build:
      context: ./clients/polly
    container_name: polly
    ports:
      - 5000:80
    environment:
      - BACKEND_HOST=http://envoy:9211
      - RESOURCE_PATH=/bytes/5000
      #- READ_TIMEOUT=700
    depends_on:
      - httpbin
      - envoy
  
  resilience4j:
    build:
      context: ./clients/resilience4j
    container_name: resilience4j
    ports:
      - 8080:8080
    environment:
      - BACKEND_HOST=http://envoy:9211
      - RESOURCE_PATH=/bytes/5000
      #- READ_TIMEOUT=700
    depends_on:
      - httpbin
      - envoy

  orchestrator:
    build: 
      context: ./orchestrator
    container_name: orchestrator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config-baseline.json:/opt/app/conf/conf.json
      #- ./config-cb.json:/opt/app/conf/conf.json
      #- ./resilience-tests:/opt/app/resilience-tests
      - /home/vagrant/.aws/credentials:/root/.aws/credentials
    environment:
      - CONFIG_FILE=/opt/app/conf/conf.json
      - AWS_BUCKET_NAME=phd-carlos-results
      - AWS_OUTPUT_PATH=resilience-tests
      # - DISK_PATH=/opt/app/resilience-tests
      - DOCKER_HOST=/var/run/docker.sock
      - TIME_ZONE=America/Sao_Paulo
    depends_on:
      - resilience4j
      - polly
      - envoy
      - httpbin

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 9000:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
  
  envoy:
    image: envoyproxy/envoy-dev
    container_name: envoy
    ports:
      - 9901:9901
      - 9211:9211
    volumes:
      - ./server/envoy.yaml:/etc/envoy/envoy.yaml
      - ./runtime:/srv/runtime
      - ./server/disable_abort_fault.sh:/disable_abort_fault.sh
      - ./server/enable_abort_fault.sh:/enable_abort_fault.sh
      - ./server/disable_delay_fault.sh:/disable_delay_fault.sh
      - ./server/enable_delay_fault.sh:/enable_delay_fault.sh
    depends_on:
      - httpbin
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
  
