version: '3.4'

services:  
  polly:
    build:
      context: ./clients/polly
    container_name: polly
    ports:
      - 5000:80
    environment:
      - BACKEND_HOST=http://envoy:9211
      - RESOURCE_PATH=/status/200
    depends_on:
      - httpbin
      - envoy
  
  resilience4j:
    build:
      context: ./clients/resilience4j
    container_name: resilience4j
    ports:
      - 8080:8080
    environment:
      - BACKEND_HOST=http://envoy:9211
      - RESOURCE_PATH=/status/200
    depends_on:
      - httpbin
      - envoy

  orchestrator:
    build: 
      context: ./orchestrator
    container_name: orchestrator
    volumes:
      - ./orchestrator/sample-conf.json:/opt/app/sample-conf.json
    environment:
      - CONFIG_FILE=/opt/app/sample-conf.json
      - OUTPUT_PATH=/opt/app
    depends_on:
      - resilience4j
      - polly

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 9000:80
  
  envoy:
    image: envoyproxy/envoy-dev
    container_name: envoy
    ports:
      - 9901:9901
      - 9211:9211
    volumes:
      - ./server/envoy.yaml:/etc/envoy/envoy.yaml
      - ./server/http_status:/srv/runtime/v1/envoy/fault/http/abort/http_status
      - ./server/abort_percent:/srv/runtime/v1/envoy/fault/http/abort/abort_percent
    depends_on:
      - httpbin

  